//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoWorking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id_event { get; set; }
        public string nama_event { get; set; }
        public string jenis_event { get; set; }
        public string waktu_event { get; set; }
        public string deskripsi { get; set; }
        public string namaFile { get; set; }
        public byte[] byteFIle { get; set; }
        public string pathFile { get; set; }
    }
}
