//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoWorking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komunitas
    {
        public int Id_komunitas { get; set; }
        public string nama_komunitas { get; set; }
        public string jenis_komunitas { get; set; }
        public string kegiatan { get; set; }
        public string namaFile { get; set; }
        public byte[] byteFile { get; set; }
        public string pathFile { get; set; }
    }
}
